<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros2_reception_orchestrator</name>
  <version>0.1.0</version>
  <description>ROS 2 reception orchestrator package</description>
  <maintainer email="dev@todo.todo">dev</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>asr_interfaces</depend>
  <depend>ros2_chat_interfaces</depend>
  <depend>ros2_vllm_interfaces</depend>
  <depend>std_msgs</depend>
  <depend>tts_msgs</depend>

  <exec_depend>asr_streaming_node</exec_depend>
  <exec_depend>mic_input_node</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros2_chat</exec_depend>
  <exec_depend>ros2_vllm</exec_depend>
  <exec_depend>tts_server</exec_depend>


  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
